language: python
python:
  - "3.5"

# command to install dependencies
install: pip install -r requirements.txt
install: pip install -r requirements-ci.txt

# script: sh run_travis.sh

script: tox
branches:
  only:
    - test-python
